apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: "{{ .Values.mssql.image.repository }}:{{ .Values.mssql.image.tag }}"
          ports:
            - containerPort: {{ .Values.mssql.port }}
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Enterprise"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.secretName }}"
                  key: "{{ .Values.mssql.passwordKey }}"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-data
