apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.configName }}"
data:
  "{{ .Values.mssql.urlKey }}": jdbc:sqlserver://mssql-service:1433;databaseName=todo_app;trustServerCertificate=true;create=true
